# Generated by Django 5.0.4 on 2024-05-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='achievements',
        ),
    ]
